version: 2.1
orbs:
  node: circleci/node@5.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  test_and_build:
    docker:
      - image: cimg/base:stable
    steps:
      # install yarn
      - node/install:
          install-yarn: true
          node-version: "16.18.0"
      # Get source code from git
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      # install backend dependencies
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ./express-storefront-backend
      # test the backend
      - run: yarn run backend:test
      # build the backend
      - run: yarn run backend:build
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true
          node-version: "16.18.0"
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ./express-storefront-backend
      - run: yarn run backend:build
      - eb/setup
      - run:
          command: |
              eb use ${EB_ENV_NAME}
              eb deploy ${EB_ENV_NAME}
              eb status
workflows:
  main:
    jobs:
      - test_and_build
      - deploy

# VS Code Extension Version: 1.1.1